name: 3. Create Certificates 
run-name: Create Certificates (${{ github.ref_name }})
on:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
  
  certificates:
    name: Create Certificates
    needs: validate
    runs-on: macos-15
    steps:
      
      # Checks-out the repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      # Patch Fastlane Match to not print tables
      - name: Patch Match Tables
        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"

      # Install project dependencies
      - name: Install Project Dependencies
        run: bundle install

      # (optional) Fastlane aktualisieren
      - name: Update Fastlane (optional)
        run: bundle update fastlane

      # Sync the GitHub runner clock with the Windows time server (workaround as suggested in https://github.com/actions/runner/issues/2996)
      - name: Sync clock
        run: sudo sntp -sS time.windows.com

      # ONE TIME ONLY: räumt alte/verwaiste Zertifikate & Profiles auf
      - name: Match Nuke (App Store) — ONE TIME ONLY
        run: bundle exec fastlane run match_nuke type:appstore skip_confirmation:true safe_remove_certs:true
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_READONLY: "false"

      # Create or update certificates for app
      - name: Create Certificates
        run: bundle exec fastlane certs
        env:
          TEAMID: ${{ secrets.TEAMID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
          MATCH_READONLY: "false"
          MATCH_FORCE_FOR_NEW_CERTIFICATES: "true"
          MATCH_SAFE_REMOVE_CERTS: "true"
